apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task
spec:
  inputs:
    params:
      - name: apikey
        description: the ibmcloud api key
      - name: region
        description: the ibmcloud region
        default: us-south
      - name: toolchainUrl
        description: the toolchain url        
  steps:
    - name: slack-webhook
      image: ibmcom/pipeline-base-image
      env:
        - name: APIKEY
          value: $(inputs.params.apikey)
        - name: REGION
          value: $(inputs.params.region)
        - name: TOOLCHAIN_URL
          value: $(inputs.params.toolchainUrl)
        - name: HOME
          value: "/root"
      command: ["/bin/sh", "-c"]
      args:
        - git clone https://github.com/VokusX/tekton_examples;
          export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
          ibmcloud config --check-version=false;
          ibmcloud login --apikey $APIKEY -r $REGION;
          TOKEN=$(ibmcloud iam oauth-tokens | cut -c 11-);
          curl -X GET ${TOOLCHAIN_URL} -H "Accept:application/json" -H "Authorization:${TOKEN}" > tekton_examples/toolchain.json;
          SLACK_WEBHOOK=$(node tekton_examples/slack_parser.js);
          curl -X POST -H 'Content-type:application/json' --data '{"text":"Tekton Pipeline ran!"}' $SLACK_WEBHOOK
    - name: git-token
      image: ibmcom/pipeline-base-image
      env:
        - name: APIKEY
          value: $(inputs.params.apikey)
        - name: REGION
          value: $(inputs.params.region)
        - name: TOOLCHAIN_URL
          value: $(inputs.params.toolchainUrl)
      command: ["/bin/sh", "-c"]
      args:
        - ls -a;
          curl -H "Accept:application/json" -H "Authorization:${TOKEN}" "https://otc-github-consolidated-broker.us-east.devops.cloud.ibm.com/github/token?git_id=github";
          curl -H "Accept:application/json" -H "Authorization:${TOKEN}" "https://otc-github-consolidated-broker.us-east.devops.cloud.ibm.com/github/token?git_id=hostedgit";
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: region
      description: the ibmcloud region
      default: us-south
    - name: toolchainUrl
      description: the toolchain url
  tasks:
    - name: pipeline-task
      taskRef:
        name: task
      params:
        - name: apikey
          value: $(params.apikey)
        - name: region
          value: $(params.region)
        - name: toolchainUrl
          value: $(params.toolchainUrl)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: region
      description: the ibmcloud registry region
      default: us-south
    - name: toolchainUrl
      description: the toolchain url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: apikey
          value: $(params.apikey)
        - name: registryRegion
          value: $(params.region)
        - name: toolchainUrl
          value: $(params.toolchainUrl)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: message
      value: binding message
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
      params:
        - name: message-l
          value: Hello from the Manual Triggers EventListener!
